# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hkilic <hkilic@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/09 14:53:33 by hkilic            #+#    #+#              #
#    Updated: 2023/05/09 14:53:33 by hkilic           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = fragtrap
SRCS = *.cpp
CMP = c++
FLAGS = -Wall -Wextra -Werror

all:
	$(CMP) $(FLAGS) $(SRCS) -o $(NAME)

clean:
	rm -f $(NAME)

fclean : clean

re: fclean all