# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hkilic <hkilic@student.42kocaeli.com.tr    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/05/09 12:18:01 by hkilic            #+#    #+#              #
#    Updated: 2023/05/09 12:18:02 by hkilic           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = Orthodox2
SRCS = *.cpp
CMP = c++
FLAGS = -Wall -Wextra -Werror

all:
	$(CMP) $(FLAGS) $(SRCS) -o $(NAME)

clean:
	rm -f $(NAME)

fclean : clean

re: fclean all